{"instance_id": "UDMIS034EXT", "instance_filename": "UDMIS034EXT_120_N120_W1.0_R0.1.qubo.json", "solver_name": "QUBODwaveSolver", "args": ["1000", "None", "None"], "timestamps": {"start": 1700862091.058573, "end": 1700862091.074195}, "solver": {"exception": "can't start new thread", "traceback": "Traceback (most recent call last):\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench.py\", line 152, in run\n    solver = self._run(instance_id, *args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\Documents\\qopt\\benchmark\\bench_qubo.py\", line 108, in _run\n    sampler = DWaveSampler(token=self.token)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\system\\samplers\\dwave_sampler.py\", line 184, in __init__\n    self.client = Client.from_config(**config)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 369, in from_config\n    return _clients[_client](**config)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\events.py\", line 105, in wrapped\n    rval = fn(*pargs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\site-packages\\dwave\\cloud\\client\\base.py\", line 581, in __init__\n    worker.start()\n  File \"C:\\ProgramData\\anaconda3\\envs\\qopt\\Lib\\threading.py\", line 957, in start\n    _start_new_thread(self._bootstrap, ())\nRuntimeError: can't start new thread\n", "fail_timestamp": 1700862091.074195}, "success": false, "version": "2.0.2"}